const airportsDenmark = [
  {
    "code": "CPH",
    "lat": "55.6205",
    "lon": "12.6495",
    "name": "Copenhagen Airport",
    "city": "Kastrup",
    "state": "Hovedstaden",
    "country": "Denmark",
    "type": "Airports",
  },
  {
    "code": "EBJ",
    "lat": "55.5247",
    "lon": "8.55388",
    "name": "Esbjerg Airport",
    "city": "Esbjerg",
    "state": "Syddanmark",
    "country": "Denmark",
    "type": "Airports",
  },
  {
    "code": "KRP",
    "lat": "56.3028",
    "lon": "9.1141",
    "name": "Karup Airport",
    "city": "K\u00e5rup",
    "state": "Midtjylland",
    "country": "Denmark",
    "type": "Airports",
  },
  {
    "code": "RNN",
    "lat": "55.0681",
    "lon": "14.7472",
    "name": "Bornholm Airport",
    "city": "Ronne",
    "state": "Hovedstaden",
    "country": "Denmark",
    "type": "Airports",
  },
  {
    "code": "SGD",
    "lat": "54.963",
    "lon": "9.78978",
    "name": "Sonderborg Airport",
    "city": "Sonderborg",
    "state": "Syddanmark",
    "country": "Denmark",
    "type": "Airports",
  },
  {
    "code": "AAL",
    "lat": "57.0952",
    "lon": "9.85606",
    "name": "Aalborg Airport",
    "city": "Norresundby",
    "state": "Nordjylland",
    "country": "Denmark",
    "type": "Airports",
  },
  {
    "code": "AAR",
    "lat": "56.3088",
    "lon": "10.6154",
    "name": "Tirstrup Airport",
    "city": "Kolind",
    "state": "Midtjylland",
    "country": "Denmark",
    "type": "Airports",
  },
  {
    "code": "BLL",
    "lat": "55.742",
    "lon": "9.15354",
    "name": "Billund Airport",
    "city": "Billund",
    "state": "Syddanmark",
    "country": "Denmark",
    "type": "Airports",
  },

 ]

 export default airportsDenmark